x-default-opts: &default-opts
  restart: unless-stopped
  tty: true
  stdin_open: true
  privileged: false
  ipc: private

services:
  unsloth:
    <<: *default-opts
    # image: unsloth/unsloth-blackwell:py311-pt2.7.1-cu128-f_xformers033
    build:
      context: .
      dockerfile: dockerfile
    container_name: unsloth
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: "all"
            capabilities: [gpu]
    ports:
      - "${JUPYTER_PORT:-48080}:${JUPYTER_PORT:-48080}"
      - "${SSH_PORT:-2222}:22"
    # volumes:
    #   - ./.cache:/workspace/.cache
    #   - ./work:/workspace/work